name: "Build and push docker image with arm64 support"
permissions: read-all
on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
        description: Name of the app to be built
      version:
        required: true
        type: string
        description: Version of the image to be built
    secrets:
      registry:
        required: true
        description: Registry to push the built image to
      user:
        required: true
        description: Registry user
      password:
        required: true
        description: Registry password
env: 
  DOCKER_TAG: ${{ secrets.registry }}/${{ inputs.app_name }}:${{ inputs.version }}
jobs:
  Build-and-Push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-docker-action@v4
        with:
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": true
              }
            }
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.registry }}
          username: ${{ secrets.user }}
          password: ${{ secrets.password }}
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          load: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.DOCKER_TAG }}
